export const killerPerks = [
    {
        name: "Bitter Murmur",
        code: "bittermurmur",
        icon: "https://static.wikia.nocookie.net/deadbydaylight_gamepedia_en/images/5/5a/IconPerks_bitterMurmur.png",
        tags: "hand,grab",
    },
    {
        name: "Claustrophobia",
        code: "claustrophobia",
        icon: "https://static.wikia.nocookie.net/deadbydaylight_gamepedia_en/images/c/c6/IconPerks_cruelLimits.png",
        tags: "person,cage",
    },
    {
        name: "Deerstalker",
        code: "deerstalker",
        icon: "https://static.wikia.nocookie.net/deadbydaylight_gamepedia_en/images/0/01/IconPerks_deerstalker.png",
        tags: "face,deer",
    },
    {
        name: "Distressing",
        code: "distressing",
        icon: "https://static.wikia.nocookie.net/deadbydaylight_gamepedia_en/images/9/94/IconPerks_distressing.png",
        tags: "heart",
    },
    {
        name: "Fearmonger",
        code: "fearmonger",
        icon: "https://static.wikia.nocookie.net/deadbydaylight_gamepedia_en/images/0/0f/IconPerks_mindbreaker.png",
        tags: "person",
    },
    {
        name: "Hex: No One Escapes Death",
        code: "hexnooneescapesdeath",
        icon: "https://static.wikia.nocookie.net/deadbydaylight_gamepedia_en/images/a/af/IconPerks_hexNoOneEscapesDeath.png",
        tags: "skull",
    },
    {
        name: "Hex: Thrill of the Hunt",
        code: "hexthrillofthehunt",
        icon: "https://static.wikia.nocookie.net/deadbydaylight_gamepedia_en/images/0/02/IconPerks_hexThrillOfTheHunt.png",
        tags: "skull,deer",
    },
    {
        name: "Insidious",
        code: "insidious",
        icon: "https://static.wikia.nocookie.net/deadbydaylight_gamepedia_en/images/4/40/IconPerks_insidious.png",
        tags: "person",
    },
    {
        name: "Iron Grasp",
        code: "irongrasp",
        icon: "https://static.wikia.nocookie.net/deadbydaylight_gamepedia_en/images/1/14/IconPerks_ironGrasp.png",
        tags: "hand,grab",
    },
    {
        name: "Jolt",
        code: "jolt",
        icon: "https://static.wikia.nocookie.net/deadbydaylight_gamepedia_en/images/3/3b/IconPerks_surge.png",
        tags: "generator,broken",
    },
    {
        name: "Scourge Hook: Monstrous Shrine",
        code: "scourgehookmonstrousshrine",
        icon: "https://static.wikia.nocookie.net/deadbydaylight_gamepedia_en/images/9/91/IconPerks_scourgeHookMonstrousShrine.png",
        tags: "hook,skull",
    },
    {
        name: "Sloppy Butcher",
        code: "sloppybutcher",
        icon: "https://static.wikia.nocookie.net/deadbydaylight_gamepedia_en/images/5/5a/IconPerks_sloppyButcher.png",
        tags: "pig",
    },
    {
        name: "Spies from the Shadows",
        code: "spiesfromtheshadows",
        icon: "https://static.wikia.nocookie.net/deadbydaylight_gamepedia_en/images/b/b1/IconPerks_spiesFromTheShadows.png",
        tags: "crow",
    },
    {
        name: "Unrelenting",
        code: "unrelenting",
        icon: "https://static.wikia.nocookie.net/deadbydaylight_gamepedia_en/images/5/57/IconPerks_unrelenting.png",
        tags: "skull,swing",
    },
    {
        name: "Whispers",
        code: "whispers",
        icon: "https://static.wikia.nocookie.net/deadbydaylight_gamepedia_en/images/b/bb/IconPerks_whispers.png",
        tags: "ear",
    },
    {
        name: "Unnerving Presence",
        code: "unnervingpresence",
        icon: "https://static.wikia.nocookie.net/deadbydaylight_gamepedia_en/images/a/a4/IconPerks_unnervingPresence.png",
        tags: "person,hand,face,scream",
    },
    {
        name: "Brutal Strength",
        code: "brutalstrength",
        icon: "https://static.wikia.nocookie.net/deadbydaylight_gamepedia_en/images/3/3d/IconPerks_brutalStrength.png",
        tags: "foot,kick",
    },
    {
        name: "Agitation",
        code: "agitation",
        icon: "https://static.wikia.nocookie.net/deadbydaylight_gamepedia_en/images/a/ac/IconPerks_agitation.png",
        tags: "mouth,teeth",
    },
    {
        name: "Predator",
        code: "predator",
        icon: "https://static.wikia.nocookie.net/deadbydaylight_gamepedia_en/images/7/73/IconPerks_predator.png",
        tags: "foot,footprint,scratch marks",
    },
    {
        name: "Bloodhound",
        code: "bloodhound",
        icon: "https://static.wikia.nocookie.net/deadbydaylight_gamepedia_en/images/e/e0/IconPerks_bloodhound.png",
        tags: "wolf,teeth",
    },
    {
        name: "Shadowborn",
        code: "shadowborn",
        icon: "https://static.wikia.nocookie.net/deadbydaylight_gamepedia_en/images/a/ac/IconPerks_shadowborn.png",
        tags: "eye",
    },
    {
        name: "Enduring",
        code: "enduring",
        icon: "https://static.wikia.nocookie.net/deadbydaylight_gamepedia_en/images/9/94/IconPerks_enduring.png",
        tags: "face",
    },
    {
        name: "Lightborn",
        code: "lightborn",
        icon: "https://static.wikia.nocookie.net/deadbydaylight_gamepedia_en/images/4/48/IconPerks_lightborn.png",
        tags: "eye",
    },
    {
        name: "Tinkerer",
        code: "tinkerer",
        icon: "https://static.wikia.nocookie.net/deadbydaylight_gamepedia_en/images/d/d9/IconPerks_tinkerer.png",
        tags: "hand,tool",
    },
    {
        name: "Stridor",
        code: "stridor",
        icon: "https://static.wikia.nocookie.net/deadbydaylight_gamepedia_en/images/3/32/IconPerks_stridor.png",
        tags: "mouth",
    },
    {
        name: "Thanatophobia",
        code: "thanatophobia",
        icon: "https://static.wikia.nocookie.net/deadbydaylight_gamepedia_en/images/a/a2/IconPerks_thanatophobia.png",
        tags: "skull",
    },
    {
        name: "A Nurse's Calling",
        code: "anursescalling",
        icon: "https://static.wikia.nocookie.net/deadbydaylight_gamepedia_en/images/f/fe/IconPerks_aNursesCalling.png",
        tags: "eye,health,skull,symbol",
    },
    {
        name: "Save the Best for Last",
        code: "savethebestforlast",
        icon: "https://static.wikia.nocookie.net/deadbydaylight_gamepedia_en/images/6/6a/IconPerks_saveTheBestForLast.png",
        tags: "person,skull,face,scream",
    },
    {
        name: "Play with Your Food",
        code: "playwithyourfood",
        icon: "https://static.wikia.nocookie.net/deadbydaylight_gamepedia_en/images/1/18/IconPerks_playWithYourFood.png",
        tags: "spider",
    },
    {
        name: "Dying Light",
        code: "dyinglight",
        icon: "https://static.wikia.nocookie.net/deadbydaylight_gamepedia_en/images/4/48/IconPerks_dyingLight.png",
        tags: "lantern",
    },
    {
        name: "Hex: The Third Seal",
        code: "hexthethirdseal",
        icon: "https://static.wikia.nocookie.net/deadbydaylight_gamepedia_en/images/3/36/IconPerks_hexTheThirdSeal.png",
        tags: "person,hand,face",
    },
    {
        name: "Hex: Ruin",
        code: "hexruin",
        icon: "https://static.wikia.nocookie.net/deadbydaylight_gamepedia_en/images/a/a2/IconPerks_hexRuin.png",
        tags: "generator",
    },
    {
        name: "Hex: Devour Hope",
        code: "hexdevourhope",
        icon: "https://static.wikia.nocookie.net/deadbydaylight_gamepedia_en/images/c/c9/IconPerks_hexDevourHope.png",
        tags: "mouth,teeth",
    },
    {
        name: "Overwhelming Presence",
        code: "overwhelmingpresence",
        icon: "https://static.wikia.nocookie.net/deadbydaylight_gamepedia_en/images/9/9a/IconPerks_overwhelmingPresence.png",
        tags: "person,symbol",
    },
    {
        name: "Monitor & Abuse",
        code: "monitorandabuse",
        icon: "https://static.wikia.nocookie.net/deadbydaylight_gamepedia_en/images/6/60/IconPerks_monitorAndAbuse.png",
        tags: "face",
    },
    {
        name: "Overcharge",
        code: "overcharge",
        icon: "https://static.wikia.nocookie.net/deadbydaylight_gamepedia_en/images/c/c3/IconPerks_overcharge.png",
        tags: "generator",
    },
    {
        name: "Beast of Prey",
        code: "beastofprey",
        icon: "https://static.wikia.nocookie.net/deadbydaylight_gamepedia_en/images/7/77/IconPerks_beastOfPrey.png",
        tags: "wolf,teeth",
    },
    {
        name: "Territorial Imperative",
        code: "territorialimperative",
        icon: "https://static.wikia.nocookie.net/deadbydaylight_gamepedia_en/images/2/2a/IconPerks_territorialImperative.png",
        tags: "wolf,teeth",
    },
    {
        name: "Hex: Huntress Lullaby",
        code: "hexhuntresslullaby",
        icon: "https://static.wikia.nocookie.net/deadbydaylight_gamepedia_en/images/1/11/IconPerks_hexHuntressLullaby.png",
        tags: "person,face,singing",
    },
    {
        name: "Knock Out",
        code: "knockout",
        icon: "https://static.wikia.nocookie.net/deadbydaylight_gamepedia_en/images/5/52/IconPerks_knockOut.png",
        tags: "person,face,hand,injury,blood",
    },
    {
        name: "Barbecue & Chilli",
        code: "barbecueandchilli",
        icon: "https://static.wikia.nocookie.net/deadbydaylight_gamepedia_en/images/5/51/IconPerks_barbecueAndChilli.png",
        tags: "person",
    },
    {
        name: "Franklin's Demise",
        code: "franklinsdemise",
        icon: "https://static.wikia.nocookie.net/deadbydaylight_gamepedia_en/images/b/b2/IconPerks_franklinsDemise.png",
        tags: "hand,flashlight",
    },
    {
        name: "Fire Up",
        code: "fireup",
        icon: "https://static.wikia.nocookie.net/deadbydaylight_gamepedia_en/images/5/5c/IconPerks_fireUp.png",
        tags: "person,fire",
    },
    {
        name: "Remember Me",
        code: "rememberme",
        icon: "https://static.wikia.nocookie.net/deadbydaylight_gamepedia_en/images/6/62/IconPerks_rememberMe.png",
        tags: "hand",
    },
    {
        name: "Blood Warden",
        code: "bloodwarden",
        icon: "https://static.wikia.nocookie.net/deadbydaylight_gamepedia_en/images/e/eb/IconPerks_bloodWarden.png",
        tags: "skull,gate",
    },
    {
        name: "Hangman's Trick",
        code: "hangmanstrick",
        icon: "https://static.wikia.nocookie.net/deadbydaylight_gamepedia_en/images/b/b4/IconPerks_hangmansTrick.png",
        tags: "hand,rope",
    },
    {
        name: "Surveillance",
        code: "surveillance",
        icon: "https://static.wikia.nocookie.net/deadbydaylight_gamepedia_en/images/e/eb/IconPerks_surveillance.png",
        tags: "person,pig,generator",
    },
    {
        name: "Make Your Choice",
        code: "makeyourchoice",
        icon: "https://static.wikia.nocookie.net/deadbydaylight_gamepedia_en/images/6/6b/IconPerks_makeYourChoice.png",
        tags: "balance,scale,symbol",
    },
    {
        name: "Bamboozle",
        code: "bamboozle",
        icon: "https://static.wikia.nocookie.net/deadbydaylight_gamepedia_en/images/7/7a/IconPerks_bamboozle.png",
        tags: "window",
    },
    {
        name: "Coulrophobia",
        code: "coulrophobia",
        icon: "https://static.wikia.nocookie.net/deadbydaylight_gamepedia_en/images/4/45/IconPerks_coulrophobia.png",
        tags: "person,face,clown",
    },
    {
        name: "Pop Goes the Weasel",
        code: "popgoestheweasel",
        icon: "https://static.wikia.nocookie.net/deadbydaylight_gamepedia_en/images/0/0f/IconPerks_popGoesTheWeasel.png",
        tags: "hook,person,jack in the box",
    },
    {
        name: "Spirit Fury",
        code: "spiritfury",
        icon: "https://static.wikia.nocookie.net/deadbydaylight_gamepedia_en/images/a/a6/IconPerks_spiritFury.png",
        tags: "window",
    },
    {
        name: "Hex: Haunted Ground",
        code: "hexhauntedground",
        icon: "https://static.wikia.nocookie.net/deadbydaylight_gamepedia_en/images/c/c4/IconPerks_hexHauntedGround.png",
        tags: "candle,skull",
    },
    {
        name: "Rancor",
        code: "rancor",
        icon: "https://static.wikia.nocookie.net/deadbydaylight_gamepedia_en/images/a/a2/IconPerks_rancor.png",
        tags: "person,face,scream",
    },
    {
        name: "Discordance",
        code: "discordance",
        icon: "https://static.wikia.nocookie.net/deadbydaylight_gamepedia_en/images/8/82/IconPerks_discordance.png",
        tags: "knife,generator,broken",
    },
    {
        name: "Mad Grit",
        code: "madgrit",
        icon: "https://static.wikia.nocookie.net/deadbydaylight_gamepedia_en/images/d/da/IconPerks_madGrit.png",
        tags: "person,hand,cloak",
    },
    {
        name: "Iron Maiden",
        code: "ironmaiden",
        icon: "https://static.wikia.nocookie.net/deadbydaylight_gamepedia_en/images/b/b0/IconPerks_ironMaiden.png",
        tags: "person",
    },
    {
        name: "Corrupt Intervention",
        code: "corruptintervention",
        icon: "https://static.wikia.nocookie.net/deadbydaylight_gamepedia_en/images/1/10/IconPerks_corruptIntervention.png",
        tags: "generator",
    },
    {
        name: "Infectious Fright",
        code: "infectiousfright",
        icon: "https://static.wikia.nocookie.net/deadbydaylight_gamepedia_en/images/6/6d/IconPerks_infectiousFright.png",
        tags: "person,face,scream",
    },
    {
        name: "Dark Devotion",
        code: "darkdevotion",
        icon: "https://static.wikia.nocookie.net/deadbydaylight_gamepedia_en/images/4/4f/IconPerks_darkDevotion.png",
        tags: "heart",
    },
    {
        name: "I'm All Ears",
        code: "imallears",
        icon: "https://static.wikia.nocookie.net/deadbydaylight_gamepedia_en/images/e/e3/IconPerks_imAllEars.png",
        tags: "face,person,auditory",
    },
    {
        name: "Thrilling Tremors",
        code: "thrillingtremors",
        icon: "https://static.wikia.nocookie.net/deadbydaylight_gamepedia_en/images/b/b8/IconPerks_thrillingTremors.png",
        tags: "person,carry",
    },
    {
        name: "Furtive Chase",
        code: "furtivechase",
        icon: "https://static.wikia.nocookie.net/deadbydaylight_gamepedia_en/images/9/94/IconPerks_furtiveChase.png",
        tags: "hook",
    },
    {
        name: "Zanshin Tactics",
        code: "zanshintactics",
        icon: "https://static.wikia.nocookie.net/deadbydaylight_gamepedia_en/images/d/d3/IconPerks_zanshinTactics.png",
        tags: "person,face",
    },
    {
        name: "Blood Echo",
        code: "bloodecho",
        icon: "https://static.wikia.nocookie.net/deadbydaylight_gamepedia_en/images/c/c3/IconPerks_bloodEcho.png",
        tags: "person,hook,injury",
    },
    {
        name: "Nemesis",
        code: "nemesis",
        icon: "https://static.wikia.nocookie.net/deadbydaylight_gamepedia_en/images/3/33/IconPerks_nemesis.png",
        tags: "face,person",
    },
    {
        name: "Gearhead",
        code: "gearhead",
        icon: "https://static.wikia.nocookie.net/deadbydaylight_gamepedia_en/images/f/fd/IconPerks_gearhead.png",
        tags: "skull,gear",
    },
    {
        name: "Dead Man's Switch",
        code: "deadmansswitch",
        icon: "https://static.wikia.nocookie.net/deadbydaylight_gamepedia_en/images/c/c3/IconPerks_deadMansSwitch.png",
        tags: "person,falling",
    },
    {
        name: "Hex: Retribution",
        code: "hexretribution",
        icon: "https://static.wikia.nocookie.net/deadbydaylight_gamepedia_en/images/a/ab/IconPerks_hexRetribution.png",
        tags: "totem,skull",
    },
    {
        name: "Forced Penance",
        code: "forcedpenance",
        icon: "https://static.wikia.nocookie.net/deadbydaylight_gamepedia_en/images/1/1d/IconPerks_forcedPenance.png",
        tags: "knife,person,carry,pyramid",
    },
    {
        name: "Trail of Torment",
        code: "trailoftorment",
        icon: "https://static.wikia.nocookie.net/deadbydaylight_gamepedia_en/images/9/94/IconPerks_trailOfTorment.png",
        tags: "generator",
    },
    {
        name: "Deathbound",
        code: "deathbound",
        icon: "https://static.wikia.nocookie.net/deadbydaylight_gamepedia_en/images/e/e7/IconPerks_deathbound.png",
        tags: "hand,rope",
    },
    {
        name: "Dragon's Grip",
        code: "dragonsgrip",
        icon: "https://static.wikia.nocookie.net/deadbydaylight_gamepedia_en/images/f/ff/IconPerks_dragonsGrip.png",
        tags: "generator,skull",
    },
    {
        name: "Hex: Blood Favour",
        code: "hexbloodfavour",
        icon: "https://static.wikia.nocookie.net/deadbydaylight_gamepedia_en/images/6/6b/IconPerks_hexBloodFavour.png",
        tags: "person,running",
    },
    {
        name: "Hex: Undying",
        code: "hexundying",
        icon: "https://static.wikia.nocookie.net/deadbydaylight_gamepedia_en/images/f/fe/IconPerks_hexUndying.png",
        tags: "totem,skull",
    },
    {
        name: "Hoarder",
        code: "hoarder",
        icon: "https://static.wikia.nocookie.net/deadbydaylight_gamepedia_en/images/2/23/IconPerks_hoarder.png",
        tags: "person",
    },
    {
        name: "Oppression",
        code: "oppression",
        icon: "https://static.wikia.nocookie.net/deadbydaylight_gamepedia_en/images/a/a1/IconPerks_oppression.png",
        tags: "hand,generator",
    },
    {
        name: "Coup de Grâce",
        code: "coupdegrace",
        icon: "https://static.wikia.nocookie.net/deadbydaylight_gamepedia_en/images/b/bd/IconPerks_coupDeGr%C3%A2ce.png",
        tags: "hook,skull",
    },
    {
        name: "Starstruck",
        code: "starstruck",
        icon: "https://static.wikia.nocookie.net/deadbydaylight_gamepedia_en/images/6/6e/IconPerks_starstruck.png",
        tags: "person,pose",
    },
    {
        name: "Hex: Crowd Control",
        code: "hexcrowdcontrol",
        icon: "https://static.wikia.nocookie.net/deadbydaylight_gamepedia_en/images/f/f1/IconPerks_hexCrowdControl.png",
        tags: "person,crowd",
    },
    {
        name: "No Way Out",
        code: "nowayout",
        icon: "https://static.wikia.nocookie.net/deadbydaylight_gamepedia_en/images/b/bb/IconPerks_noWayOut.png",
        tags: "gate",
    },
    {
        name: "Lethal Pursuer",
        code: "lethalpursuer",
        icon: "https://static.wikia.nocookie.net/deadbydaylight_gamepedia_en/images/6/61/IconPerks_lethalPursuer.png",
        tags: "person,running",
    },
    {
        name: "Hysteria",
        code: "hysteria",
        icon: "https://static.wikia.nocookie.net/deadbydaylight_gamepedia_en/images/3/3a/IconPerks_hysteria.png",
        tags: "person,face,scream,blood,injury",
    },
    {
        name: "Eruption",
        code: "eruption",
        icon: "https://static.wikia.nocookie.net/deadbydaylight_gamepedia_en/images/d/dd/IconPerks_eruption.png",
        tags: "generator",
    },
    {
        name: "Deadlock",
        code: "deadlock",
        icon: "https://static.wikia.nocookie.net/deadbydaylight_gamepedia_en/images/d/d3/IconPerks_deadlock.png",
        tags: "chain,face,generator",
    },
    {
        name: "Hex: Plaything",
        code: "hexplaything",
        icon: "https://static.wikia.nocookie.net/deadbydaylight_gamepedia_en/images/1/18/IconPerks_hexPlaything.png",
        tags: "person,face,scream",
    },
    {
        name: "Scourge Hook: Gift of Pain",
        code: "scourgehookgiftofpain",
        icon: "https://static.wikia.nocookie.net/deadbydaylight_gamepedia_en/images/2/26/IconPerks_scourgeHookGiftOfPain.png",
        tags: "person,injury,blood,hook",
    },
    {
        name: "Grim Embrace",
        code: "grimembrace",
        icon: "https://static.wikia.nocookie.net/deadbydaylight_gamepedia_en/images/1/1c/IconPerks_grimEmbrace.png",
        tags: "hand",
    },
    {
        name: "Scourge Hook: Pain Resonance",
        code: "scourgehookresonance",
        icon: "https://static.wikia.nocookie.net/deadbydaylight_gamepedia_en/images/7/79/IconPerks_scourgeHookPainResonance.png",
        tags: "hook,generator",
    },
    {
        name: "Hex: Pentimento",
        code: "hexpentimento",
        icon: "https://static.wikia.nocookie.net/deadbydaylight_gamepedia_en/images/5/5d/IconPerks_hexPentimento.png",
        tags: "hand,totem,skull",
    },
    {
        name: "Scourge Hook: Floods of Rage",
        code: "scourgehookfloodsofrage",
        icon: "https://static.wikia.nocookie.net/deadbydaylight_gamepedia_en/images/1/1c/IconPerks_scourgeHookFloodsOfRage.png",
        tags: "hook,water,rain",
    },
    {
        name: "Call of Brine",
        code: "callofbrine",
        icon: "https://static.wikia.nocookie.net/deadbydaylight_gamepedia_en/images/3/3b/IconPerks_callOfBrine.png",
        tags: "eye",
    },
    {
        name: "Merciless Storm",
        code: "mercilessstorm",
        icon: "https://static.wikia.nocookie.net/deadbydaylight_gamepedia_en/images/3/36/IconPerks_mercilessStorm.png",
        tags: "person,rain",
    },
    {
        name: "Dissolution",
        code: "dissolution",
        icon: "https://static.wikia.nocookie.net/deadbydaylight_gamepedia_en/images/1/1d/IconPerks_dissolution.png",
        tags: "pallet,foot,broken",
    },
    {
        name: "Darkness Revealed",
        code: "darknessrevealed",
        icon: "https://static.wikia.nocookie.net/deadbydaylight_gamepedia_en/images/e/ed/IconPerks_darknessRevealed.png",
        tags: "locker,hand",
    },
    {
        name: "Septic Touch",
        code: "septictouch",
        icon: "https://static.wikia.nocookie.net/deadbydaylight_gamepedia_en/images/d/d8/IconPerks_septicTouch.png",
        tags: "hand",
    },
    {
        name: "Shattered Hope",
        code: "shatteredhope",
        icon: "https://static.wikia.nocookie.net/deadbydaylight_gamepedia_en/images/a/aa/IconPerks_shatteredHope.png",
        tags: "hand",
    },
    {
        name: "Superior Anatomy",
        code: "superioranatomy",
        icon: "https://static.wikia.nocookie.net/deadbydaylight_gamepedia_en/images/4/4a/IconPerks_superiorAnatomy.png",
        tags: "person,vault,window,knife",
    },
    {
        name: "Awakened Awareness",
        code: "awakenedawareness",
        icon: "https://static.wikia.nocookie.net/deadbydaylight_gamepedia_en/images/9/97/IconPerks_awakenedAwareness.png",
        tags: "person,face,sun glasses",
    },
    {
        name: "Terminus",
        code: "terminus",
        icon: "https://static.wikia.nocookie.net/deadbydaylight_gamepedia_en/images/4/4c/IconPerks_terminus.png",
        tags: "person,chair",
    },
    {
        name: "Nowhere to Hide",
        code: "nowheretohide",
        icon: "https://static.wikia.nocookie.net/deadbydaylight_gamepedia_en/images/2/29/IconPerks_nowhereToHide.png",
        tags: "knight,sword",
    },
    {
        name: "Hex: Face the Darkness",
        code: "hexfacetthedarkness",
        icon: "https://static.wikia.nocookie.net/deadbydaylight_gamepedia_en/images/a/af/IconPerks_hexFaceTheDarkness.png",
        tags: "knight,sword",
    },
    {
        name: "Hubris",
        code: "hubris",
        icon: "https://static.wikia.nocookie.net/deadbydaylight_gamepedia_en/images/a/aa/IconPerks_hubris.png",
        tags: "hand,sword,skull,broken",
    },
];
