export const survivorPerks = [
    {
        name: "Dark Sense",
        code: "darksense",
        icon: "https://static.wikia.nocookie.net/deadbydaylight_gamepedia_en/images/9/92/IconPerks_darkSense.png",
        tags: "eye,person",
    },
    {
        name: "Déjà Vu",
        code: "dejavu",
        icon: "https://static.wikia.nocookie.net/deadbydaylight_gamepedia_en/images/8/89/IconPerks_dejaVu.png",
        tags: "eye,spiral",
    },
    {
        name: "Guardian",
        code: "guardian",
        icon: "https://static.wikia.nocookie.net/deadbydaylight_gamepedia_en/images/2/23/IconPerks_guardian.png",
        tags: "person,running",
    },
    {
        name: "Hope",
        code: "hope",
        icon: "https://static.wikia.nocookie.net/deadbydaylight_gamepedia_en/images/1/18/IconPerks_hope.png",
        tags: "wings",
    },
    {
        name: "Inner Healing",
        code: "innerhealing",
        icon: "https://static.wikia.nocookie.net/deadbydaylight_gamepedia_en/images/d/df/IconPerks_innerHealing.png",
        tags: "person,hood",
    },
    {
        name: "Kindred",
        code: "kindred",
        icon: "https://static.wikia.nocookie.net/deadbydaylight_gamepedia_en/images/a/a8/IconPerks_kindred.png",
        tags: "eye,hook",
    },
    {
        name: "Kinship",
        code: "kinship",
        icon: "https://static.wikia.nocookie.net/deadbydaylight_gamepedia_en/images/1/1d/IconPerks_camaraderie.png",
        tags: "hook",
    },
    {
        name: "Lightweight",
        code: "lightweight",
        icon: "https://static.wikia.nocookie.net/deadbydaylight_gamepedia_en/images/6/67/IconPerks_lightweight.png",
        tags: "feather",
    },
    {
        name: "No One Left Behind",
        code: "nooneleftbehind",
        icon: "https://static.wikia.nocookie.net/deadbydaylight_gamepedia_en/images/b/b0/IconPerks_noOneLeftBehind.png",
        tags: "person",
    },
    {
        name: "Plunderer's Instinct",
        code: "plunderersinstinct",
        icon: "https://static.wikia.nocookie.net/deadbydaylight_gamepedia_en/images/2/28/IconPerks_plunderersInstinct.png",
        tags: "chest",
    },
    {
        name: "Premonition",
        code: "premonition",
        icon: "https://static.wikia.nocookie.net/deadbydaylight_gamepedia_en/images/3/39/IconPerks_premonition.png",
        tags: "person,auditory",
    },
    {
        name: "Renewal",
        code: "renewal",
        icon: "https://static.wikia.nocookie.net/deadbydaylight_gamepedia_en/images/7/7b/IconPerks_renewal.png",
        tags: "person,injury,crouch",
    },
    {
        name: "Resilience",
        code: "resilience",
        icon: "https://static.wikia.nocookie.net/deadbydaylight_gamepedia_en/images/e/ee/IconPerks_resilience.png",
        tags: "person,fist",
    },
    {
        name: "Self-Aware",
        code: "selfaware",
        icon: "https://static.wikia.nocookie.net/deadbydaylight_gamepedia_en/images/7/7c/IconPerks_fixated.png",
        tags: "feet,scratch marks",
    },
    {
        name: "Situational Awareness",
        code: "situationalawareness",
        icon: "https://static.wikia.nocookie.net/deadbydaylight_gamepedia_en/images/d/da/IconPerks_situationalAwareness.png",
        tags: "person",
    },
    {
        name: "Slippery Meat",
        code: "slipperymeat",
        icon: "https://static.wikia.nocookie.net/deadbydaylight_gamepedia_en/images/0/03/IconPerks_slipperyMeat.png",
        tags: "hook,steak",
    },
    {
        name: "Small Game",
        code: "smallgame",
        icon: "https://static.wikia.nocookie.net/deadbydaylight_gamepedia_en/images/d/dc/IconPerks_smallGame.png",
        tags: "totem,skull,auditory",
    },
    {
        name: "Spine Chill",
        code: "spinechill",
        icon: "https://static.wikia.nocookie.net/deadbydaylight_gamepedia_en/images/5/57/IconPerks_spineChill.png",
        tags: "cat,auditory",
    },
    {
        name: "This Is Not Happening",
        code: "thisisnothappening",
        icon: "https://static.wikia.nocookie.net/deadbydaylight_gamepedia_en/images/5/58/IconPerks_thisIsNotHappening.png",
        tags: "person",
    },
    {
        name: "We'll Make It",
        code: "wellmakeit",
        icon: "https://static.wikia.nocookie.net/deadbydaylight_gamepedia_en/images/8/8a/IconPerks_wellMakeIt.png",
        tags: "person,hook",
    },
    {
        name: "Bond",
        code: "bond",
        icon: "https://static.wikia.nocookie.net/deadbydaylight_gamepedia_en/images/a/a0/IconPerks_bond.png",
        tags: "hand,rope",
    },
    {
        name: "Prove Thyself",
        code: "provethyself",
        icon: "https://static.wikia.nocookie.net/deadbydaylight_gamepedia_en/images/0/0f/IconPerks_proveThyself.png",
        tags: "person",
    },
    {
        name: "Leader",
        code: "leader",
        icon: "https://static.wikia.nocookie.net/deadbydaylight_gamepedia_en/images/3/3d/IconPerks_leader.png",
        tags: "person,pointing,pose",
    },
    {
        name: "Quick & Quiet",
        code: "quickandquiet",
        icon: "https://static.wikia.nocookie.net/deadbydaylight_gamepedia_en/images/1/14/IconPerks_quickAndQuiet.png",
        tags: "person,crouch",
    },
    {
        name: "Sprint Burst",
        code: "sprintburst",
        icon: "https://static.wikia.nocookie.net/deadbydaylight_gamepedia_en/images/e/e4/IconPerks_sprintBurst.png",
        tags: "foot,running",
    },
    {
        name: "Adrenaline",
        code: "adrenaline",
        icon: "https://static.wikia.nocookie.net/deadbydaylight_gamepedia_en/images/f/f7/IconPerks_adrenaline.png",
        tags: "heart,syringe",
    },
    {
        name: "Empathy",
        code: "empathy",
        icon: "https://static.wikia.nocookie.net/deadbydaylight_gamepedia_en/images/a/ae/IconPerks_empathy.png",
        tags: "heart,hand",
    },
    {
        name: "Botany Knowledge",
        code: "bodanyknowledge",
        icon: "https://static.wikia.nocookie.net/deadbydaylight_gamepedia_en/images/1/1e/IconPerks_botanyKnowledge.png",
        tags: "plant",
    },
    {
        name: "Self-Care",
        code: "selfcare",
        icon: "https://static.wikia.nocookie.net/deadbydaylight_gamepedia_en/images/b/b2/IconPerks_self-Care.png",
        tags: "hand,bandage",
    },
    {
        name: "Iron Will",
        code: "ironwill",
        icon: "https://static.wikia.nocookie.net/deadbydaylight_gamepedia_en/images/5/58/IconPerks_ironWill.png",
        tags: "person,face,bite",
    },
    {
        name: "Calm Spirit",
        code: "calmspirit",
        icon: "https://static.wikia.nocookie.net/deadbydaylight_gamepedia_en/images/6/6c/IconPerks_calmSpirit.png",
        tags: "hand,bird",
    },
    {
        name: "Saboteur",
        code: "saboteur",
        icon: "https://static.wikia.nocookie.net/deadbydaylight_gamepedia_en/images/0/0e/IconPerks_saboteur.png",
        tags: "hook,broken",
    },
    {
        name: "Balanced Landing",
        code: "balancedlanding",
        icon: "https://static.wikia.nocookie.net/deadbydaylight_gamepedia_en/images/5/5e/IconPerks_balancedLanding.png",
        tags: "person,pose",
    },
    {
        name: "Urban Evasion",
        code: "urbanevasion",
        icon: "https://static.wikia.nocookie.net/deadbydaylight_gamepedia_en/images/c/c7/IconPerks_urbanEvasion.png",
        tags: "person,crouch",
    },
    {
        name: "Streetwise",
        code: "streetwise",
        icon: "https://static.wikia.nocookie.net/deadbydaylight_gamepedia_en/images/f/ff/IconPerks_streetwise.png",
        tags: "grafitti",
    },
    {
        name: "Left Behind",
        code: "leftbehind",
        icon: "https://static.wikia.nocookie.net/deadbydaylight_gamepedia_en/images/c/c3/IconPerks_leftBehind.png",
        tags: "person,crouch",
    },
    {
        name: "Borrowed Time",
        code: "borrowedtime",
        icon: "https://static.wikia.nocookie.net/deadbydaylight_gamepedia_en/images/a/a3/IconPerks_borrowedTime.png",
        tags: "hand,clock",
    },
    {
        name: "Unbreakable",
        code: "unbreakable",
        icon: "https://static.wikia.nocookie.net/deadbydaylight_gamepedia_en/images/4/4a/IconPerks_unbreakable.png",
        tags: "person,face",
    },
    {
        name: "We're Gonna Live Forever",
        code: "weregonnaliveforever",
        icon: "https://static.wikia.nocookie.net/deadbydaylight_gamepedia_en/images/b/b8/IconPerks_wereGonnaLiveForever.png",
        tags: "person,pose",
    },
    {
        name: "Dead Hard",
        code: "deadhard",
        icon: "https://static.wikia.nocookie.net/deadbydaylight_gamepedia_en/images/7/75/IconPerks_deadHard.png",
        tags: "person,running",
    },
    {
        name: "No Mither",
        code: "nomither",
        icon: "https://static.wikia.nocookie.net/deadbydaylight_gamepedia_en/images/f/f5/IconPerks_noMither.png",
        tags: "person",
    },
    {
        name: "Sole Survivor",
        code: "solesurvivor",
        icon: "https://static.wikia.nocookie.net/deadbydaylight_gamepedia_en/images/8/8e/IconPerks_soleSurvivor.png",
        tags: "person,skull",
    },
    {
        name: "Object of Obsession",
        code: "objectofobsession",
        icon: "https://static.wikia.nocookie.net/deadbydaylight_gamepedia_en/images/2/2b/IconPerks_objectOfObsession.png",
        tags: "eye",
    },
    {
        name: "Decisive Strike",
        code: "decisivestrike",
        icon: "https://static.wikia.nocookie.net/deadbydaylight_gamepedia_en/images/e/ee/IconPerks_decisiveStrike.png",
        tags: "hand",
    },
    {
        name: "Open-Handed",
        code: "openhanded",
        icon: "https://static.wikia.nocookie.net/deadbydaylight_gamepedia_en/images/5/5d/IconPerks_open-Handed.png",
        tags: "hand,card",
    },
    {
        name: "Up the Ante",
        code: "uptheante",
        icon: "https://static.wikia.nocookie.net/deadbydaylight_gamepedia_en/images/a/a3/IconPerks_upTheAnte.png",
        tags: "hand",
    },
    {
        name: "Ace in the Hole",
        code: "aceinthehole",
        icon: "https://static.wikia.nocookie.net/deadbydaylight_gamepedia_en/images/2/24/IconPerks_aceInTheHole.png",
        tags: "hand,card",
    },
    {
        name: "Technician",
        code: "technician",
        icon: "https://static.wikia.nocookie.net/deadbydaylight_gamepedia_en/images/6/62/IconPerks_technician.png",
        tags: "hand,face,gear",
    },
    {
        name: "Lithe",
        code: "lithe",
        icon: "https://static.wikia.nocookie.net/deadbydaylight_gamepedia_en/images/c/cc/IconPerks_lithe.png",
        tags: "person,jump",
    },
    {
        name: "Alert",
        code: "alert",
        icon: "https://static.wikia.nocookie.net/deadbydaylight_gamepedia_en/images/7/71/IconPerks_alert.png",
        tags: "person,face",
    },
    {
        name: "Wake Up!",
        code: "wakeup",
        icon: "https://static.wikia.nocookie.net/deadbydaylight_gamepedia_en/images/f/fd/IconPerks_wakeUp.png",
        tags: "face,eye",
    },
    {
        name: "Pharmacy",
        code: "pharmacy",
        icon: "https://static.wikia.nocookie.net/deadbydaylight_gamepedia_en/images/f/f1/IconPerks_pharmacy.png",
        tags: "hand,health",
    },
    {
        name: "Vigil",
        code: "vigil",
        icon: "https://static.wikia.nocookie.net/deadbydaylight_gamepedia_en/images/4/46/IconPerks_vigil.png",
        tags: "person,crouch,lantern",
    },
    {
        name: "Tenacity",
        code: "tenacity",
        icon: "https://static.wikia.nocookie.net/deadbydaylight_gamepedia_en/images/9/9d/IconPerks_tenacity.png",
        tags: "person,hand",
    },
    {
        name: "Detective's Hunch",
        code: "detectiveshunch",
        icon: "https://static.wikia.nocookie.net/deadbydaylight_gamepedia_en/images/7/7b/IconPerks_detectivesHunch.png",
        tags: "person,tv",
    },
    {
        name: "Stake Out",
        code: "stakeout",
        icon: "https://static.wikia.nocookie.net/deadbydaylight_gamepedia_en/images/c/cd/IconPerks_stakeOut.png",
        tags: "person,hiding",
    },
    {
        name: "Dance With Me",
        code: "dancewithme",
        icon: "https://static.wikia.nocookie.net/deadbydaylight_gamepedia_en/images/1/17/IconPerks_danceWithMe.png",
        tags: "foot",
    },
    {
        name: "Windows of Opportunity",
        code: "windowsofopportunity",
        icon: "https://static.wikia.nocookie.net/deadbydaylight_gamepedia_en/images/1/17/IconPerks_windowsOfOpportunity.png",
        tags: "eye,window",
    },
    {
        name: "Boil Over",
        code: "boilover",
        icon: "https://static.wikia.nocookie.net/deadbydaylight_gamepedia_en/images/f/f5/IconPerks_boilOver.png",
        tags: "horse",
    },
    {
        name: "Diversion",
        code: "diversion",
        icon: "https://static.wikia.nocookie.net/deadbydaylight_gamepedia_en/images/a/a6/IconPerks_diversion.png",
        tags: "hand,throw",
    },
    {
        name: "Deliverance",
        code: "deliverance",
        icon: "https://static.wikia.nocookie.net/deadbydaylight_gamepedia_en/images/7/7e/IconPerks_deliverance.png",
        tags: "hook,person",
    },
    {
        name: "Autodidact",
        code: "autodidact",
        icon: "https://static.wikia.nocookie.net/deadbydaylight_gamepedia_en/images/9/96/IconPerks_autodidact.png",
        tags: "book",
    },
    {
        name: "Breakdown",
        code: "breakdown",
        icon: "https://static.wikia.nocookie.net/deadbydaylight_gamepedia_en/images/6/6c/IconPerks_breakdown.png",
        tags: "person,hook,broken",
    },
    {
        name: "Aftercare",
        code: "aftercare",
        icon: "https://static.wikia.nocookie.net/deadbydaylight_gamepedia_en/images/0/0d/IconPerks_aftercare.png",
        tags: "hand",
    },
    {
        name: "Distortion",
        code: "distortion",
        icon: "https://static.wikia.nocookie.net/deadbydaylight_gamepedia_en/images/4/41/IconPerks_distortion.png",
        tags: "person",
    },
    {
        name: "Solidarity",
        code: "solidarity",
        icon: "https://static.wikia.nocookie.net/deadbydaylight_gamepedia_en/images/9/9e/IconPerks_solidarity.png",
        tags: "person",
    },
    {
        name: "Poised",
        code: "poised",
        icon: "https://static.wikia.nocookie.net/deadbydaylight_gamepedia_en/images/5/52/IconPerks_poised.png",
        tags: "person,generator",
    },
    {
        name: "Head On",
        code: "headon",
        icon: "https://static.wikia.nocookie.net/deadbydaylight_gamepedia_en/images/c/cb/IconPerks_headOn.png",
        tags: "person,locker",
    },
    {
        name: "Flip-Flop",
        code: "flipflop",
        icon: "https://static.wikia.nocookie.net/deadbydaylight_gamepedia_en/images/3/31/IconPerks_flip-Flop.png",
        tags: "person,face,wink",
    },
    {
        name: "Buckle Up",
        code: "buckleup",
        icon: "https://static.wikia.nocookie.net/deadbydaylight_gamepedia_en/images/7/74/IconPerks_buckleUp.png",
        tags: "person,face,hand",
    },
    {
        name: "Mettle of Man",
        code: "mettleofman",
        icon: "https://static.wikia.nocookie.net/deadbydaylight_gamepedia_en/images/5/52/IconPerks_mettleOfMan.png",
        tags: "hand",
    },
    {
        name: "Lucky Break",
        code: "luckybreak",
        icon: "https://static.wikia.nocookie.net/deadbydaylight_gamepedia_en/images/a/a7/IconPerks_luckyBreak.png",
        tags: "hand",
    },
    {
        name: "Any Means Necessary",
        code: "anymeansnecessary",
        icon: "https://static.wikia.nocookie.net/deadbydaylight_gamepedia_en/images/7/79/IconPerks_anyMeansNecessary.png",
        tags: "person,pose",
    },
    {
        name: "Breakout",
        code: "breakout",
        icon: "https://static.wikia.nocookie.net/deadbydaylight_gamepedia_en/images/d/d0/IconPerks_breakout.png",
        tags: "person,motorcycle",
    },
    {
        name: "Off the Record",
        code: "offtherecord",
        icon: "https://static.wikia.nocookie.net/deadbydaylight_gamepedia_en/images/9/9e/IconPerks_offTheRecord.png",
        tags: "hand,broken",
    },
    {
        name: "Red Herring",
        code: "redherring",
        icon: "https://static.wikia.nocookie.net/deadbydaylight_gamepedia_en/images/1/1c/IconPerks_redHerring.png",
        tags: "fish",
    },
    {
        name: "For the People",
        code: "forthepeople",
        icon: "https://static.wikia.nocookie.net/deadbydaylight_gamepedia_en/images/3/31/IconPerks_forThePeople.png",
        tags: "person,flag",
    },
    {
        name: "Soul Guard",
        code: "soulguard",
        icon: "https://static.wikia.nocookie.net/deadbydaylight_gamepedia_en/images/a/a5/IconPerks_soulGuard.png",
        tags: "hand",
    },
    {
        name: "Blood Pact",
        code: "bloodpact",
        icon: "https://static.wikia.nocookie.net/deadbydaylight_gamepedia_en/images/c/c9/IconPerks_bloodPact.png",
        tags: "hand",
    },
    {
        name: "Repressed Alliance",
        code: "repressedalliance",
        icon: "https://static.wikia.nocookie.net/deadbydaylight_gamepedia_en/images/3/31/IconPerks_repressedAlliance.png",
        tags: "hand",
    },
    {
        name: "Visionary",
        code: "visionary",
        icon: "https://static.wikia.nocookie.net/deadbydaylight_gamepedia_en/images/7/7c/IconPerks_visionary.png",
        tags: "person,face",
    },
    {
        name: "Desperate Measures",
        code: "desperatemeasures",
        icon: "https://static.wikia.nocookie.net/deadbydaylight_gamepedia_en/images/8/84/IconPerks_desperateMeasures.png",
        tags: "person,hook",
    },
    {
        name: "Built to Last",
        code: "builttolast",
        icon: "https://static.wikia.nocookie.net/deadbydaylight_gamepedia_en/images/3/3b/IconPerks_builtToLast.png",
        tags: "person,ruler",
    },
    {
        name: "Appraisal",
        code: "appraisal",
        icon: "https://static.wikia.nocookie.net/deadbydaylight_gamepedia_en/images/c/c1/IconPerks_appraisal.png",
        tags: "person,face,hand",
    },
    {
        name: "Deception",
        code: "deception",
        icon: "https://static.wikia.nocookie.net/deadbydaylight_gamepedia_en/images/e/eb/IconPerks_deception.png",
        tags: "hand",
    },
    {
        name: "Power Struggle",
        code: "powerstruggle",
        icon: "https://static.wikia.nocookie.net/deadbydaylight_gamepedia_en/images/4/4b/IconPerks_powerStruggle.png",
        tags: "hand,rope",
    },
    {
        name: "Fast Track",
        code: "fasttrack",
        icon: "https://static.wikia.nocookie.net/deadbydaylight_gamepedia_en/images/7/75/IconPerks_fastTrack.png",
        tags: "person,skull",
    },
    {
        name: "Smash Hit",
        code: "smashhit",
        icon: "https://static.wikia.nocookie.net/deadbydaylight_gamepedia_en/images/e/e0/IconPerks_smashHit.png",
        tags: "symbol",
    },
    {
        name: "Self-Preservation",
        code: "selfpreservation",
        icon: "https://static.wikia.nocookie.net/deadbydaylight_gamepedia_en/images/4/43/IconPerks_self-Preservation.png",
        tags: "person,hiding",
    },
    {
        name: "Counterforce",
        code: "counterforce",
        icon: "https://static.wikia.nocookie.net/deadbydaylight_gamepedia_en/images/d/d1/IconPerks_counterforce.png",
        tags: "eye,totem,skull",
    },
    {
        name: "Resurgence",
        code: "resurgence",
        icon: "https://static.wikia.nocookie.net/deadbydaylight_gamepedia_en/images/f/f3/IconPerks_resurgence.png",
        tags: "person",
    },
    {
        name: "Blast Mine",
        code: "blastmine",
        icon: "https://static.wikia.nocookie.net/deadbydaylight_gamepedia_en/images/1/1c/IconPerks_blastMine.png",
        tags: "hand",
    },
    {
        name: "Bite the Bullet",
        code: "bitethebullet",
        icon: "https://static.wikia.nocookie.net/deadbydaylight_gamepedia_en/images/a/a5/IconPerks_biteTheBullet.png",
        tags: "person,face,hand",
    },
    {
        name: "Flashbang",
        code: "flashbang",
        icon: "https://static.wikia.nocookie.net/deadbydaylight_gamepedia_en/images/d/db/IconPerks_flashbang.png",
        tags: "hand,grenade",
    },
    {
        name: "Rookie Spirit",
        code: "rookiespirit",
        icon: "https://static.wikia.nocookie.net/deadbydaylight_gamepedia_en/images/2/2f/IconPerks_rookieSpirit.png",
        tags: "eye,generator",
    },
    {
        name: "Clairvoyance",
        code: "clairvoyance",
        icon: "https://static.wikia.nocookie.net/deadbydaylight_gamepedia_en/images/9/91/IconPerks_clairvoyance.png",
        tags: "person,hand,face",
    },
    {
        name: "Boon: Circle of Healing",
        code: "booncircleofhealing",
        icon: "https://static.wikia.nocookie.net/deadbydaylight_gamepedia_en/images/5/54/IconPerks_boonCircleOfHealing.png",
        tags: "health,symbol",
    },
    {
        name: "Boon: Shadow Step",
        code: "boonshadowstep",
        icon: "https://static.wikia.nocookie.net/deadbydaylight_gamepedia_en/images/c/c7/IconPerks_boonShadowStep.png",
        tags: "foot",
    },
    {
        name: "Overcome",
        code: "overcome",
        icon: "https://static.wikia.nocookie.net/deadbydaylight_gamepedia_en/images/8/82/IconPerks_overcome.png",
        tags: "person,running",
    },
    {
        name: "Corrective Action",
        code: "correctiveaction",
        icon: "https://static.wikia.nocookie.net/deadbydaylight_gamepedia_en/images/4/4f/IconPerks_correctiveAction.png",
        tags: "person,pose",
    },
    {
        name: "Boon: Exponential",
        code: "boonexponential",
        icon: "https://static.wikia.nocookie.net/deadbydaylight_gamepedia_en/images/7/76/IconPerks_boonExponential.png",
        tags: "hand",
    },
    {
        name: "Parental Guidance",
        code: "parentalguidance",
        icon: "https://static.wikia.nocookie.net/deadbydaylight_gamepedia_en/images/4/46/IconPerks_parentalGuidance.png",
        tags: "person,umbrella",
    },
    {
        name: "Empathic Connection",
        code: "empathicconnection",
        icon: "https://static.wikia.nocookie.net/deadbydaylight_gamepedia_en/images/1/14/IconPerks_empathicConnection.png",
        tags: "person",
    },
    {
        name: "Boon: Dark Theory",
        code: "boondarktheory",
        icon: "https://static.wikia.nocookie.net/deadbydaylight_gamepedia_en/images/6/60/IconPerks_boonDarkTheory.png",
        tags: "person",
    },
    {
        name: "Inner Focus",
        code: "innerfocus",
        icon: "https://static.wikia.nocookie.net/deadbydaylight_gamepedia_en/images/7/7e/IconPerks_innerFocus.png",
        tags: "skull,eye",
    },
    {
        name: "Residual Manifest",
        code: "residualmanifest",
        icon: "https://static.wikia.nocookie.net/deadbydaylight_gamepedia_en/images/d/d0/IconPerks_residualManifest.png",
        tags: "hand,flashlight",
    },
    {
        name: "Overzealous",
        code: "overzealous",
        icon: "https://static.wikia.nocookie.net/deadbydaylight_gamepedia_en/images/9/99/IconPerks_overzealous.png",
        tags: "person",
    },
];
