export const killerPerks = [
    {
        name: "Bitter Murmur",
        code: "bittermurmur",
        icon: "5/5a/IconPerks_bitterMurmur",
        tags: "hand,grab",
    },
    {
        name: "Claustrophobia",
        code: "claustrophobia",
        icon: "c/c6/IconPerks_cruelLimits",
        tags: "person,cage",
    },
    {
        name: "Deerstalker",
        code: "deerstalker",
        icon: "0/01/IconPerks_deerstalker",
        tags: "face,deer",
    },
    {
        name: "Distressing",
        code: "distressing",
        icon: "9/94/IconPerks_distressing",
        tags: "heart",
    },
    {
        name: "Fearmonger",
        code: "fearmonger",
        icon: "0/0f/IconPerks_mindbreaker",
        tags: "person",
    },
    {
        name: "Hex: No One Escapes Death",
        code: "hexnooneescapesdeath",
        icon: "a/af/IconPerks_hexNoOneEscapesDeath",
        tags: "skull",
    },
    {
        name: "Hex: Thrill of the Hunt",
        code: "hexthrillofthehunt",
        icon: "0/02/IconPerks_hexThrillOfTheHunt",
        tags: "skull,deer",
    },
    {
        name: "Insidious",
        code: "insidious",
        icon: "4/40/IconPerks_insidious",
        tags: "person",
    },
    {
        name: "Iron Grasp",
        code: "irongrasp",
        icon: "1/14/IconPerks_ironGrasp",
        tags: "hand,grab",
    },
    {
        name: "Jolt",
        code: "jolt",
        icon: "3/3b/IconPerks_surge",
        tags: "generator,broken",
    },
    {
        name: "Scourge Hook: Monstrous Shrine",
        code: "scourgehookmonstrousshrine",
        icon: "9/91/IconPerks_scourgeHookMonstrousShrine",
        tags: "hook,skull",
    },
    {
        name: "Sloppy Butcher",
        code: "sloppybutcher",
        icon: "5/5a/IconPerks_sloppyButcher",
        tags: "pig",
    },
    {
        name: "Spies from the Shadows",
        code: "spiesfromtheshadows",
        icon: "b/b1/IconPerks_spiesFromTheShadows",
        tags: "crow",
    },
    {
        name: "Unrelenting",
        code: "unrelenting",
        icon: "5/57/IconPerks_unrelenting",
        tags: "skull,swing",
    },
    {
        name: "Whispers",
        code: "whispers",
        icon: "b/bb/IconPerks_whispers",
        tags: "ear",
    },
    {
        name: "Unnerving Presence",
        code: "unnervingpresence",
        icon: "a/a4/IconPerks_unnervingPresence",
        tags: "person,hand,face,scream",
    },
    {
        name: "Brutal Strength",
        code: "brutalstrength",
        icon: "3/3d/IconPerks_brutalStrength",
        tags: "foot,kick",
    },
    {
        name: "Agitation",
        code: "agitation",
        icon: "a/ac/IconPerks_agitation",
        tags: "mouth,teeth",
    },
    {
        name: "Predator",
        code: "predator",
        icon: "7/73/IconPerks_predator",
        tags: "foot,footprint,scratch marks",
    },
    {
        name: "Bloodhound",
        code: "bloodhound",
        icon: "e/e0/IconPerks_bloodhound",
        tags: "wolf,teeth",
    },
    {
        name: "Shadowborn",
        code: "shadowborn",
        icon: "a/ac/IconPerks_shadowborn",
        tags: "eye",
    },
    {
        name: "Enduring",
        code: "enduring",
        icon: "9/94/IconPerks_enduring",
        tags: "face",
    },
    {
        name: "Lightborn",
        code: "lightborn",
        icon: "4/48/IconPerks_lightborn",
        tags: "eye",
    },
    {
        name: "Tinkerer",
        code: "tinkerer",
        icon: "d/d9/IconPerks_tinkerer",
        tags: "hand,tool",
    },
    {
        name: "Stridor",
        code: "stridor",
        icon: "3/32/IconPerks_stridor",
        tags: "mouth",
    },
    {
        name: "Thanatophobia",
        code: "thanatophobia",
        icon: "a/a2/IconPerks_thanatophobia",
        tags: "skull",
    },
    {
        name: "A Nurse's Calling",
        code: "anursescalling",
        icon: "f/fe/IconPerks_aNursesCalling",
        tags: "eye,health,skull,symbol",
    },
    {
        name: "Save the Best for Last",
        code: "savethebestforlast",
        icon: "6/6a/IconPerks_saveTheBestForLast",
        tags: "person,skull,face,scream",
    },
    {
        name: "Play with Your Food",
        code: "playwithyourfood",
        icon: "1/18/IconPerks_playWithYourFood",
        tags: "spider",
    },
    {
        name: "Dying Light",
        code: "dyinglight",
        icon: "4/48/IconPerks_dyingLight",
        tags: "lantern",
    },
    {
        name: "Hex: The Third Seal",
        code: "hexthethirdseal",
        icon: "3/36/IconPerks_hexTheThirdSeal",
        tags: "person,hand,face",
    },
    {
        name: "Hex: Ruin",
        code: "hexruin",
        icon: "a/a2/IconPerks_hexRuin",
        tags: "generator",
    },
    {
        name: "Hex: Devour Hope",
        code: "hexdevourhope",
        icon: "c/c9/IconPerks_hexDevourHope",
        tags: "mouth,teeth",
    },
    {
        name: "Overwhelming Presence",
        code: "overwhelmingpresence",
        icon: "9/9a/IconPerks_overwhelmingPresence",
        tags: "person,symbol",
    },
    {
        name: "Monitor & Abuse",
        code: "monitorandabuse",
        icon: "6/60/IconPerks_monitorAndAbuse",
        tags: "face",
    },
    {
        name: "Overcharge",
        code: "overcharge",
        icon: "c/c3/IconPerks_overcharge",
        tags: "generator",
    },
    {
        name: "Beast of Prey",
        code: "beastofprey",
        icon: "7/77/IconPerks_beastOfPrey",
        tags: "wolf,teeth",
    },
    {
        name: "Territorial Imperative",
        code: "territorialimperative",
        icon: "2/2a/IconPerks_territorialImperative",
        tags: "wolf,teeth",
    },
    {
        name: "Hex: Huntress Lullaby",
        code: "hexhuntresslullaby",
        icon: "1/11/IconPerks_hexHuntressLullaby",
        tags: "person,face,singing",
    },
    {
        name: "Knock Out",
        code: "knockout",
        icon: "5/52/IconPerks_knockOut",
        tags: "person,face,hand,injury,blood",
    },
    {
        name: "Barbecue & Chilli",
        code: "barbecueandchilli",
        icon: "5/51/IconPerks_barbecueAndChilli",
        tags: "person",
    },
    {
        name: "Franklin's Demise",
        code: "franklinsdemise",
        icon: "b/b2/IconPerks_franklinsDemise",
        tags: "hand,flashlight",
    },
    {
        name: "Fire Up",
        code: "fireup",
        icon: "5/5c/IconPerks_fireUp",
        tags: "person,fire",
    },
    {
        name: "Remember Me",
        code: "rememberme",
        icon: "6/62/IconPerks_rememberMe",
        tags: "hand",
    },
    {
        name: "Blood Warden",
        code: "bloodwarden",
        icon: "e/eb/IconPerks_bloodWarden",
        tags: "skull,gate",
    },
    {
        name: "Hangman's Trick",
        code: "hangmanstrick",
        icon: "b/b4/IconPerks_hangmansTrick",
        tags: "hand,rope",
    },
    {
        name: "Surveillance",
        code: "surveillance",
        icon: "e/eb/IconPerks_surveillance",
        tags: "person,pig,generator",
    },
    {
        name: "Make Your Choice",
        code: "makeyourchoice",
        icon: "6/6b/IconPerks_makeYourChoice",
        tags: "balance,scale,symbol",
    },
    {
        name: "Bamboozle",
        code: "bamboozle",
        icon: "7/7a/IconPerks_bamboozle",
        tags: "window",
    },
    {
        name: "Coulrophobia",
        code: "coulrophobia",
        icon: "4/45/IconPerks_coulrophobia",
        tags: "person,face,clown",
    },
    {
        name: "Pop Goes the Weasel",
        code: "popgoestheweasel",
        icon: "0/0f/IconPerks_popGoesTheWeasel",
        tags: "hook,person,jack in the box",
    },
    {
        name: "Spirit Fury",
        code: "spiritfury",
        icon: "a/a6/IconPerks_spiritFury",
        tags: "window",
    },
    {
        name: "Hex: Haunted Ground",
        code: "hexhauntedground",
        icon: "c/c4/IconPerks_hexHauntedGround",
        tags: "candle,skull",
    },
    {
        name: "Rancor",
        code: "rancor",
        icon: "a/a2/IconPerks_rancor",
        tags: "person,face,scream",
    },
    {
        name: "Discordance",
        code: "discordance",
        icon: "8/82/IconPerks_discordance",
        tags: "knife,generator,broken",
    },
    {
        name: "Mad Grit",
        code: "madgrit",
        icon: "d/da/IconPerks_madGrit",
        tags: "person,hand,cloak",
    },
    {
        name: "Iron Maiden",
        code: "ironmaiden",
        icon: "b/b0/IconPerks_ironMaiden",
        tags: "person",
    },
    {
        name: "Corrupt Intervention",
        code: "corruptintervention",
        icon: "1/10/IconPerks_corruptIntervention",
        tags: "generator",
    },
    {
        name: "Infectious Fright",
        code: "infectiousfright",
        icon: "6/6d/IconPerks_infectiousFright",
        tags: "person,face,scream",
    },
    {
        name: "Dark Devotion",
        code: "darkdevotion",
        icon: "4/4f/IconPerks_darkDevotion",
        tags: "heart",
    },
    {
        name: "I'm All Ears",
        code: "imallears",
        icon: "e/e3/IconPerks_imAllEars",
        tags: "face,person,auditory",
    },
    {
        name: "Thrilling Tremors",
        code: "thrillingtremors",
        icon: "b/b8/IconPerks_thrillingTremors",
        tags: "person,carry",
    },
    {
        name: "Furtive Chase",
        code: "furtivechase",
        icon: "9/94/IconPerks_furtiveChase",
        tags: "hook",
    },
    {
        name: "Zanshin Tactics",
        code: "zanshintactics",
        icon: "d/d3/IconPerks_zanshinTactics",
        tags: "person,face",
    },
    {
        name: "Blood Echo",
        code: "bloodecho",
        icon: "c/c3/IconPerks_bloodEcho",
        tags: "person,hook,injury",
    },
    {
        name: "Nemesis",
        code: "nemesis",
        icon: "3/33/IconPerks_nemesis",
        tags: "face,person",
    },
    {
        name: "Gearhead",
        code: "gearhead",
        icon: "f/fd/IconPerks_gearhead",
        tags: "skull,gear",
    },
    {
        name: "Dead Man's Switch",
        code: "deadmansswitch",
        icon: "c/c3/IconPerks_deadMansSwitch",
        tags: "person,falling",
    },
    {
        name: "Hex: Retribution",
        code: "hexretribution",
        icon: "a/ab/IconPerks_hexRetribution",
        tags: "totem,skull",
    },
    {
        name: "Forced Penance",
        code: "forcedpenance",
        icon: "1/1d/IconPerks_forcedPenance",
        tags: "knife,person,carry,pyramid",
    },
    {
        name: "Trail of Torment",
        code: "trailoftorment",
        icon: "9/94/IconPerks_trailOfTorment",
        tags: "generator",
    },
    {
        name: "Deathbound",
        code: "deathbound",
        icon: "e/e7/IconPerks_deathbound",
        tags: "hand,rope",
    },
    {
        name: "Dragon's Grip",
        code: "dragonsgrip",
        icon: "f/ff/IconPerks_dragonsGrip",
        tags: "generator,skull",
    },
    {
        name: "Hex: Blood Favour",
        code: "hexbloodfavour",
        icon: "6/6b/IconPerks_hexBloodFavour",
        tags: "person,running",
    },
    {
        name: "Hex: Undying",
        code: "hexundying",
        icon: "f/fe/IconPerks_hexUndying",
        tags: "totem,skull",
    },
    {
        name: "Hoarder",
        code: "hoarder",
        icon: "2/23/IconPerks_hoarder",
        tags: "person,teapot",
    },
    {
        name: "Oppression",
        code: "oppression",
        icon: "a/a1/IconPerks_oppression",
        tags: "hand,generator",
    },
    {
        name: "Coup de Grâce",
        code: "coupdegrace",
        icon: "b/bd/IconPerks_coupDeGr%C3%A2ce",
        tags: "hook,skull",
    },
    {
        name: "Starstruck",
        code: "starstruck",
        icon: "6/6e/IconPerks_starstruck",
        tags: "person,pose",
    },
    {
        name: "Hex: Crowd Control",
        code: "hexcrowdcontrol",
        icon: "f/f1/IconPerks_hexCrowdControl",
        tags: "person,crowd",
    },
    {
        name: "No Way Out",
        code: "nowayout",
        icon: "b/bb/IconPerks_noWayOut",
        tags: "gate",
    },
    {
        name: "Lethal Pursuer",
        code: "lethalpursuer",
        icon: "6/61/IconPerks_lethalPursuer",
        tags: "person,running",
    },
    {
        name: "Hysteria",
        code: "hysteria",
        icon: "3/3a/IconPerks_hysteria",
        tags: "person,face,scream,blood,injury",
    },
    {
        name: "Eruption",
        code: "eruption",
        icon: "d/dd/IconPerks_eruption",
        tags: "generator",
    },
    {
        name: "Deadlock",
        code: "deadlock",
        icon: "d/d3/IconPerks_deadlock",
        tags: "chain,face,generator",
    },
    {
        name: "Hex: Plaything",
        code: "hexplaything",
        icon: "1/18/IconPerks_hexPlaything",
        tags: "person,face,scream",
    },
    {
        name: "Scourge Hook: Gift of Pain",
        code: "scourgehookgiftofpain",
        icon: "2/26/IconPerks_scourgeHookGiftOfPain",
        tags: "person,injury,blood,hook",
    },
    {
        name: "Grim Embrace",
        code: "grimembrace",
        icon: "1/1c/IconPerks_grimEmbrace",
        tags: "hand",
    },
    {
        name: "Scourge Hook: Pain Resonance",
        code: "scourgehookresonance",
        icon: "7/79/IconPerks_scourgeHookPainResonance",
        tags: "hook,generator",
    },
    {
        name: "Hex: Pentimento",
        code: "hexpentimento",
        icon: "5/5d/IconPerks_hexPentimento",
        tags: "hand,totem,skull",
    },
    {
        name: "Scourge Hook: Floods of Rage",
        code: "scourgehookfloodsofrage",
        icon: "1/1c/IconPerks_scourgeHookFloodsOfRage",
        tags: "hook,water,rain",
    },
    {
        name: "Call of Brine",
        code: "callofbrine",
        icon: "3/3b/IconPerks_callOfBrine",
        tags: "eye",
    },
    {
        name: "Merciless Storm",
        code: "mercilessstorm",
        icon: "3/36/IconPerks_mercilessStorm",
        tags: "person,rain",
    },
    {
        name: "Dissolution",
        code: "dissolution",
        icon: "1/1d/IconPerks_dissolution",
        tags: "pallet,foot,broken",
    },
    {
        name: "Darkness Revealed",
        code: "darknessrevealed",
        icon: "e/ed/IconPerks_darknessRevealed",
        tags: "locker,hand",
    },
    {
        name: "Septic Touch",
        code: "septictouch",
        icon: "d/d8/IconPerks_septicTouch",
        tags: "hand",
    },
    {
        name: "Shattered Hope",
        code: "shatteredhope",
        icon: "a/aa/IconPerks_shatteredHope",
        tags: "hand",
    },
    {
        name: "Superior Anatomy",
        code: "superioranatomy",
        icon: "4/4a/IconPerks_superiorAnatomy",
        tags: "person,vaulting,window,knife",
    },
    {
        name: "Awakened Awareness",
        code: "awakenedawareness",
        icon: "9/97/IconPerks_awakenedAwareness",
        tags: "person,face,sun glasses",
    },
    {
        name: "Terminus",
        code: "terminus",
        icon: "4/4c/IconPerks_terminus",
        tags: "person,chair",
    },
    {
        name: "Nowhere to Hide",
        code: "nowheretohide",
        icon: "2/29/IconPerks_nowhereToHide",
        tags: "knight,sword",
    },
    {
        name: "Hex: Face the Darkness",
        code: "hexfacetthedarkness",
        icon: "a/af/IconPerks_hexFaceTheDarkness",
        tags: "knight,sword",
    },
    {
        name: "Hubris",
        code: "hubris",
        icon: "a/aa/IconPerks_hubris",
        tags: "hand,sword,skull,broken",
    },
    {
        name: "THWACK!",
        code: "thwack",
        icon: "b/bb/IconPerks_thwack",
        tags: "face",
    },
    {
        name: "Leverage",
        code: "leverage",
        icon: "c/c6/IconPerks_leverage",
        tags: "person,claw,hook",
    },
    {
        name: "Game Afoot",
        code: "gameafoot",
        icon: "5/53/IconPerks_gameAfoot",
        tags: "person,claw",
    },
    {
        name: "Genetic Limits",
        code: "geneticlimits",
        icon: "6/6d/IconPerks_geneticLimits",
        tags: "person,dna",
    },
    {
        name: "Forced Hesitation",
        code: "forcedhesitation",
        icon: "4/4c/IconPerks_forcedHesitation",
        tags: "person,sword,claw",
    },
    {
        name: "Machine Learning",
        code: "machinelearning",
        icon: "0/01/IconPerks_machineLearning",
        tags: "person,sword,claw",
    },
    {
        name: "Rapid Brutality",
        code: "rapidbrutality",
        icon: "d/d4/IconPerks_rapidBrutality",
        tags: "alien,running",
    },
    {
        name: "Alien Instinct",
        code: "alieninstinct",
        icon: "3/34/IconPerks_alienInstinct",
        tags: "alien,hand",
    },
    {
        name: "Ultimate Weapon",
        code: "ultimateweapon",
        icon: "8/8a/IconPerks_ultimateWeapon",
        tags: "alien",
    },
];
