export const survivorPerks = [
    {
        name: "Dark Sense",
        code: "darksense",
        icon: "9/92/IconPerks_darkSense",
        tags: "eye,person",
    },
    {
        name: "Déjà Vu",
        code: "dejavu",
        icon: "8/89/IconPerks_dejaVu",
        tags: "eye,spiral",
    },
    {
        name: "Guardian",
        code: "guardian",
        icon: "2/23/IconPerks_guardian",
        tags: "person,running",
    },
    {
        name: "Hope",
        code: "hope",
        icon: "1/18/IconPerks_hope",
        tags: "wings",
    },
    {
        name: "Inner Healing",
        code: "innerhealing",
        icon: "d/df/IconPerks_innerHealing",
        tags: "person,hood",
    },
    {
        name: "Kindred",
        code: "kindred",
        icon: "a/a8/IconPerks_kindred",
        tags: "eye,hook",
    },
    {
        name: "Kinship",
        code: "kinship",
        icon: "1/1d/IconPerks_camaraderie",
        tags: "hook",
    },
    {
        name: "Lightweight",
        code: "lightweight",
        icon: "6/67/IconPerks_lightweight",
        tags: "feather",
    },
    {
        name: "No One Left Behind",
        code: "nooneleftbehind",
        icon: "b/b0/IconPerks_noOneLeftBehind",
        tags: "person",
    },
    {
        name: "Plunderer's Instinct",
        code: "plunderersinstinct",
        icon: "2/28/IconPerks_plunderersInstinct",
        tags: "chest",
    },
    {
        name: "Premonition",
        code: "premonition",
        icon: "3/39/IconPerks_premonition",
        tags: "person,auditory",
    },
    {
        name: "Renewal",
        code: "renewal",
        icon: "7/7b/IconPerks_renewal",
        tags: "person,injury,crouch",
    },
    {
        name: "Resilience",
        code: "resilience",
        icon: "e/ee/IconPerks_resilience",
        tags: "person,fist",
    },
    {
        name: "Self-Aware",
        code: "selfaware",
        icon: "7/7c/IconPerks_fixated",
        tags: "feet,scratch marks",
    },
    {
        name: "Situational Awareness",
        code: "situationalawareness",
        icon: "d/da/IconPerks_situationalAwareness",
        tags: "person",
    },
    {
        name: "Slippery Meat",
        code: "slipperymeat",
        icon: "0/03/IconPerks_slipperyMeat",
        tags: "hook,steak",
    },
    {
        name: "Small Game",
        code: "smallgame",
        icon: "d/dc/IconPerks_smallGame",
        tags: "totem,skull,auditory",
    },
    {
        name: "Spine Chill",
        code: "spinechill",
        icon: "5/57/IconPerks_spineChill",
        tags: "cat,auditory",
    },
    {
        name: "This Is Not Happening",
        code: "thisisnothappening",
        icon: "5/58/IconPerks_thisIsNotHappening",
        tags: "person",
    },
    {
        name: "We'll Make It",
        code: "wellmakeit",
        icon: "8/8a/IconPerks_wellMakeIt",
        tags: "person,hook",
    },
    {
        name: "Bond",
        code: "bond",
        icon: "a/a0/IconPerks_bond",
        tags: "hand,rope",
    },
    {
        name: "Prove Thyself",
        code: "provethyself",
        icon: "0/0f/IconPerks_proveThyself",
        tags: "person",
    },
    {
        name: "Leader",
        code: "leader",
        icon: "3/3d/IconPerks_leader",
        tags: "person,pointing,pose",
    },
    {
        name: "Quick & Quiet",
        code: "quickandquiet",
        icon: "1/14/IconPerks_quickAndQuiet",
        tags: "person,crouch",
    },
    {
        name: "Sprint Burst",
        code: "sprintburst",
        icon: "e/e4/IconPerks_sprintBurst",
        tags: "foot,running",
    },
    {
        name: "Adrenaline",
        code: "adrenaline",
        icon: "f/f7/IconPerks_adrenaline",
        tags: "heart,syringe",
    },
    {
        name: "Empathy",
        code: "empathy",
        icon: "a/ae/IconPerks_empathy",
        tags: "heart,hand",
    },
    {
        name: "Botany Knowledge",
        code: "bodanyknowledge",
        icon: "1/1e/IconPerks_botanyKnowledge",
        tags: "plant",
    },
    {
        name: "Self-Care",
        code: "selfcare",
        icon: "b/b2/IconPerks_self-Care",
        tags: "hand,bandage",
    },
    {
        name: "Iron Will",
        code: "ironwill",
        icon: "5/58/IconPerks_ironWill",
        tags: "person,face,bite",
    },
    {
        name: "Calm Spirit",
        code: "calmspirit",
        icon: "6/6c/IconPerks_calmSpirit",
        tags: "hand,bird",
    },
    {
        name: "Saboteur",
        code: "saboteur",
        icon: "0/0e/IconPerks_saboteur",
        tags: "hook,broken",
    },
    {
        name: "Balanced Landing",
        code: "balancedlanding",
        icon: "5/5e/IconPerks_balancedLanding",
        tags: "person,pose",
    },
    {
        name: "Urban Evasion",
        code: "urbanevasion",
        icon: "c/c7/IconPerks_urbanEvasion",
        tags: "person,crouch",
    },
    {
        name: "Streetwise",
        code: "streetwise",
        icon: "f/ff/IconPerks_streetwise",
        tags: "grafitti",
    },
    {
        name: "Left Behind",
        code: "leftbehind",
        icon: "c/c3/IconPerks_leftBehind",
        tags: "person,crouch",
    },
    {
        name: "Borrowed Time",
        code: "borrowedtime",
        icon: "a/a3/IconPerks_borrowedTime",
        tags: "hand,clock",
    },
    {
        name: "Unbreakable",
        code: "unbreakable",
        icon: "4/4a/IconPerks_unbreakable",
        tags: "person,face",
    },
    {
        name: "We're Gonna Live Forever",
        code: "weregonnaliveforever",
        icon: "b/b8/IconPerks_wereGonnaLiveForever",
        tags: "person,pose",
    },
    {
        name: "Dead Hard",
        code: "deadhard",
        icon: "7/75/IconPerks_deadHard",
        tags: "person,running",
    },
    {
        name: "No Mither",
        code: "nomither",
        icon: "f/f5/IconPerks_noMither",
        tags: "person",
    },
    {
        name: "Sole Survivor",
        code: "solesurvivor",
        icon: "8/8e/IconPerks_soleSurvivor",
        tags: "person,skull",
    },
    {
        name: "Object of Obsession",
        code: "objectofobsession",
        icon: "2/2b/IconPerks_objectOfObsession",
        tags: "eye",
    },
    {
        name: "Decisive Strike",
        code: "decisivestrike",
        icon: "e/ee/IconPerks_decisiveStrike",
        tags: "hand",
    },
    {
        name: "Open-Handed",
        code: "openhanded",
        icon: "5/5d/IconPerks_open-Handed",
        tags: "hand,card",
    },
    {
        name: "Up the Ante",
        code: "uptheante",
        icon: "a/a3/IconPerks_upTheAnte",
        tags: "hand",
    },
    {
        name: "Ace in the Hole",
        code: "aceinthehole",
        icon: "2/24/IconPerks_aceInTheHole",
        tags: "hand,card",
    },
    {
        name: "Technician",
        code: "technician",
        icon: "6/62/IconPerks_technician",
        tags: "hand,face,gear",
    },
    {
        name: "Lithe",
        code: "lithe",
        icon: "c/cc/IconPerks_lithe",
        tags: "person,vaulting",
    },
    {
        name: "Alert",
        code: "alert",
        icon: "7/71/IconPerks_alert",
        tags: "person,face",
    },
    {
        name: "Wake Up!",
        code: "wakeup",
        icon: "f/fd/IconPerks_wakeUp",
        tags: "face,eye",
    },
    {
        name: "Pharmacy",
        code: "pharmacy",
        icon: "f/f1/IconPerks_pharmacy",
        tags: "hand,health",
    },
    {
        name: "Vigil",
        code: "vigil",
        icon: "4/46/IconPerks_vigil",
        tags: "person,crouch,lantern",
    },
    {
        name: "Tenacity",
        code: "tenacity",
        icon: "9/9d/IconPerks_tenacity",
        tags: "person,hand,blood,injury",
    },
    {
        name: "Detective's Hunch",
        code: "detectiveshunch",
        icon: "7/7b/IconPerks_detectivesHunch",
        tags: "person,tv",
    },
    {
        name: "Stake Out",
        code: "stakeout",
        icon: "c/cd/IconPerks_stakeOut",
        tags: "person,hiding",
    },
    {
        name: "Dance With Me",
        code: "dancewithme",
        icon: "1/17/IconPerks_danceWithMe",
        tags: "foot",
    },
    {
        name: "Windows of Opportunity",
        code: "windowsofopportunity",
        icon: "1/17/IconPerks_windowsOfOpportunity",
        tags: "eye,window",
    },
    {
        name: "Boil Over",
        code: "boilover",
        icon: "f/f5/IconPerks_boilOver",
        tags: "horse",
    },
    {
        name: "Diversion",
        code: "diversion",
        icon: "a/a6/IconPerks_diversion",
        tags: "hand,throw",
    },
    {
        name: "Deliverance",
        code: "deliverance",
        icon: "7/7e/IconPerks_deliverance",
        tags: "hook,person",
    },
    {
        name: "Autodidact",
        code: "autodidact",
        icon: "9/96/IconPerks_autodidact",
        tags: "book",
    },
    {
        name: "Breakdown",
        code: "breakdown",
        icon: "6/6c/IconPerks_breakdown",
        tags: "person,hook,broken",
    },
    {
        name: "Aftercare",
        code: "aftercare",
        icon: "0/0d/IconPerks_aftercare",
        tags: "hand,fist",
    },
    {
        name: "Distortion",
        code: "distortion",
        icon: "4/41/IconPerks_distortion",
        tags: "person",
    },
    {
        name: "Solidarity",
        code: "solidarity",
        icon: "9/9e/IconPerks_solidarity",
        tags: "person",
    },
    {
        name: "Poised",
        code: "poised",
        icon: "5/52/IconPerks_poised",
        tags: "person,generator",
    },
    {
        name: "Head On",
        code: "headon",
        icon: "c/cb/IconPerks_headOn",
        tags: "person,locker",
    },
    {
        name: "Flip-Flop",
        code: "flipflop",
        icon: "3/31/IconPerks_flip-Flop",
        tags: "person,face,wink",
    },
    {
        name: "Buckle Up",
        code: "buckleup",
        icon: "7/74/IconPerks_buckleUp",
        tags: "person,face,hand,grab",
    },
    {
        name: "Mettle of Man",
        code: "mettleofman",
        icon: "5/52/IconPerks_mettleOfMan",
        tags: "hand,fist",
    },
    {
        name: "Lucky Break",
        code: "luckybreak",
        icon: "a/a7/IconPerks_luckyBreak",
        tags: "hand,grab",
    },
    {
        name: "Any Means Necessary",
        code: "anymeansnecessary",
        icon: "7/79/IconPerks_anyMeansNecessary",
        tags: "person,pose",
    },
    {
        name: "Breakout",
        code: "breakout",
        icon: "d/d0/IconPerks_breakout",
        tags: "person,motorcycle",
    },
    {
        name: "Off the Record",
        code: "offtherecord",
        icon: "9/9e/IconPerks_offTheRecord",
        tags: "hand,broken,grab",
    },
    {
        name: "Red Herring",
        code: "redherring",
        icon: "1/1c/IconPerks_redHerring",
        tags: "fish",
    },
    {
        name: "For the People",
        code: "forthepeople",
        icon: "3/31/IconPerks_forThePeople",
        tags: "person,flag",
    },
    {
        name: "Soul Guard",
        code: "soulguard",
        icon: "a/a5/IconPerks_soulGuard",
        tags: "hand,grab",
    },
    {
        name: "Blood Pact",
        code: "bloodpact",
        icon: "c/c9/IconPerks_bloodPact",
        tags: "hand",
    },
    {
        name: "Repressed Alliance",
        code: "repressedalliance",
        icon: "3/31/IconPerks_repressedAlliance",
        tags: "hand",
    },
    {
        name: "Visionary",
        code: "visionary",
        icon: "7/7c/IconPerks_visionary",
        tags: "person,face",
    },
    {
        name: "Desperate Measures",
        code: "desperatemeasures",
        icon: "8/84/IconPerks_desperateMeasures",
        tags: "person,hook",
    },
    {
        name: "Built to Last",
        code: "builttolast",
        icon: "3/3b/IconPerks_builtToLast",
        tags: "person,ruler",
    },
    {
        name: "Appraisal",
        code: "appraisal",
        icon: "c/c1/IconPerks_appraisal",
        tags: "person,face,hand,grab",
    },
    {
        name: "Deception",
        code: "deception",
        icon: "e/eb/IconPerks_deception",
        tags: "hand",
    },
    {
        name: "Power Struggle",
        code: "powerstruggle",
        icon: "4/4b/IconPerks_powerStruggle",
        tags: "hand,rope",
    },
    {
        name: "Fast Track",
        code: "fasttrack",
        icon: "7/75/IconPerks_fastTrack",
        tags: "person,skull",
    },
    {
        name: "Smash Hit",
        code: "smashhit",
        icon: "e/e0/IconPerks_smashHit",
        tags: "symbol",
    },
    {
        name: "Self-Preservation",
        code: "selfpreservation",
        icon: "4/43/IconPerks_self-Preservation",
        tags: "person,hiding",
    },
    {
        name: "Counterforce",
        code: "counterforce",
        icon: "d/d1/IconPerks_counterforce",
        tags: "eye,totem,skull",
    },
    {
        name: "Resurgence",
        code: "resurgence",
        icon: "f/f3/IconPerks_resurgence",
        tags: "person",
    },
    {
        name: "Blast Mine",
        code: "blastmine",
        icon: "1/1c/IconPerks_blastMine",
        tags: "hand,grab",
    },
    {
        name: "Bite the Bullet",
        code: "bitethebullet",
        icon: "a/a5/IconPerks_biteTheBullet",
        tags: "person,face,hand",
    },
    {
        name: "Flashbang",
        code: "flashbang",
        icon: "d/db/IconPerks_flashbang",
        tags: "hand,grenade",
    },
    {
        name: "Rookie Spirit",
        code: "rookiespirit",
        icon: "2/2f/IconPerks_rookieSpirit",
        tags: "eye,generator",
    },
    {
        name: "Clairvoyance",
        code: "clairvoyance",
        icon: "9/91/IconPerks_clairvoyance",
        tags: "person,hand,face",
    },
    {
        name: "Boon: Circle of Healing",
        code: "booncircleofhealing",
        icon: "5/54/IconPerks_boonCircleOfHealing",
        tags: "health,symbol",
    },
    {
        name: "Boon: Shadow Step",
        code: "boonshadowstep",
        icon: "c/c7/IconPerks_boonShadowStep",
        tags: "foot",
    },
    {
        name: "Overcome",
        code: "overcome",
        icon: "8/82/IconPerks_overcome",
        tags: "person,running",
    },
    {
        name: "Corrective Action",
        code: "correctiveaction",
        icon: "4/4f/IconPerks_correctiveAction",
        tags: "person,pose",
    },
    {
        name: "Boon: Exponential",
        code: "boonexponential",
        icon: "7/76/IconPerks_boonExponential",
        tags: "hand",
    },
    {
        name: "Parental Guidance",
        code: "parentalguidance",
        icon: "4/46/IconPerks_parentalGuidance",
        tags: "person,umbrella",
    },
    {
        name: "Empathic Connection",
        code: "empathicconnection",
        icon: "1/14/IconPerks_empathicConnection",
        tags: "person",
    },
    {
        name: "Boon: Dark Theory",
        code: "boondarktheory",
        icon: "6/60/IconPerks_boonDarkTheory",
        tags: "person",
    },
    {
        name: "Inner Focus",
        code: "innerfocus",
        icon: "7/7e/IconPerks_innerFocus",
        tags: "skull,eye",
    },
    {
        name: "Residual Manifest",
        code: "residualmanifest",
        icon: "d/d0/IconPerks_residualManifest",
        tags: "hand,flashlight",
    },
    {
        name: "Overzealous",
        code: "overzealous",
        icon: "9/99/IconPerks_overzealous",
        tags: "person",
    },
    {
        name: "Wiretap",
        code: "wiretap",
        icon: "2/23/IconPerks_wiretap",
        tags: "person,face",
    },
    {
        name: "Reactive Healing",
        code: "reactivehealing",
        icon: "5/5a/IconPerks_reactiveHealing",
        tags: "person,health,bandage",
    },
    {
        name: "Low Profile",
        code: "lowprofile",
        icon: "f/fb/IconPerks_lowProfile",
        tags: "foot,shoe",
    },
    {
        name: "Better than New",
        code: "betterthannew",
        icon: "b/b1/IconPerks_betterThanNew",
        tags: "person,hand",
    },
    {
        name: "Reassurance",
        code: "reassurance",
        icon: "5/5b/IconPerks_reassurance",
        tags: "person,hand,thumb",
    },
    {
        name: "Hyperfocus",
        code: "hyperfocus",
        icon: "5/5d/IconPerks_hyperfocus",
        tags: "person,face",
    },
    {
        name: "Potential Energy",
        code: "potentialenergy",
        icon: "0/07/IconPerks_potentialEnergy",
        tags: "person,hand,symbol",
    },
    {
        name: "Fogwise",
        code: "fogwise",
        icon: "9/90/IconPerks_fogwise",
        tags: "face,eye",
    },
    {
        name: "Quick Gambit",
        code: "quickgambit",
        icon: "f/f7/IconPerks_quickGambit",
        tags: "person,running",
    },
    {
        name: "Friendly Competition",
        code: "friendlycompetition",
        icon: "4/4c/IconPerks_friendlyCompetition",
        tags: "hand,wrench",
    },
    {
        name: "Teamwork: Power of Two",
        code: "teamworkpoweroftwo",
        icon: "2/2b/IconPerks_teamworkPowerOfTwo",
        tags: "person,running",
    },
    {
        name: "Cut Loose",
        code: "cutloose",
        icon: "0/02/IconPerks_cutLoose",
        tags: "person,face,hand,window,vaulting",
    },
    {
        name: "Blood Rush",
        code: "bloodrush",
        icon: "2/2c/IconPerks_bloodRush",
        tags: "person,heart",
    },
    {
        name: "Teamwork: Collective Stealth",
        code: "teamworkcollectivestealth",
        icon: "a/a0/IconPerks_teamworkCollectiveStealth",
        tags: "person",
    },
    {
        name: "Background Player",
        code: "backgroundplayer",
        icon: "e/e8/IconPerks_backgroundPlayer",
        tags: "person,running",
    },
    {
        name: "Troubleshooter",
        code: "troubleshooter",
        icon: "0/0d/IconPerks_troubleshooter",
        tags: "eye,generator,person",
    },
    {
        name: "Made for This",
        code: "madeforthis",
        icon: "c/c0/IconPerks_madeForThis",
        tags: "person,running",
    },
    {
        name: "Scavenger",
        code: "scavenger",
        icon: "c/c6/IconPerks_scavenger",
        tags: "person,toolbox,box",
    },
    {
        name: "Dramaturgy",
        code: "dramaturgy",
        icon: "8/85/IconPerks_dramaturgy",
        tags: "person,face,mask,hand",
    },
    {
        name: "Scene Partner",
        code: "scenepartner",
        icon: "b/b4/IconPerks_scenePartner",
        tags: "person,knife",
    },
    {
        name: "Plot Twist",
        code: "plottwist",
        icon: "a/ac/IconPerks_plotTwist",
        tags: "person,bandage,injury,pose",
    },
    {
        name: "Chemical Trap",
        code: "chemicaltrap",
        icon: "9/9a/IconPerks_chemicalTrap",
        tags: "bomb",
    },
    {
        name: "Light-Footed",
        code: "lightfooted",
        icon: "e/e5/IconPerks_light-Footed",
        tags: "foot,running",
    },
    {
        name: "Lucky Star",
        code: "luckystar",
        icon: "0/08/IconPerks_luckyStar",
        tags: "person,face",
    },
];
